### PR TITLE
Images and Anchor Points for `DrawableNode`

### PR DESCRIPTION
**Pull request by cj-dimaano**
This adds support for images and anchor points.

### CODE REVIEW

**Review by Sheyne — APPROVED** [review]
Do you want to `export type Point = { x: number, y: number }`?

**Comment by cj-dimaano** [comment]
That's probably a good idea.

**Comment by Sheyne** [comment]
If you make a commit that does it, I'll merge it real quick. No need to use the commit syntax that will trigger a release though.

**Comment by cj-dimaano** [comment]
I'm on the train right now, but I could get that done when I get to class,
if you're willing to wait that long.

**Comment by Sheyne** [comment]
Yeah, no hurry.

**Pull request merged**
