### PR TITLE
feat(Value): Maps can be passed to programs

### PR DESCRIPTION
**Pull request by Sheyne**
BREAKING CHANGE: the whole Program API

New version of core:

https://github.com/2graphic/sinap-core/releases/download/serialize-maps/sinap-core-0.0.0-development.tgz

**BREAKING CHANGES TO NOTE**

When creating a new `Program` object, you now:

```
const prog = new Program(model, context.global["plugin-stub"].Program);
```

Pass it a model, and the plugin `Program` class, rather than an instance of the plugin `Program` class. I can fix these changes if you let me know what branch to do it on.

### CODE REVIEW

**Comment by Sheyne** [comment]
@RighteousRaichu for an example of how to pass a `Map` to a `Program`:

```{TypeScript}
// can specify map type in some other way
// in this example the type of start is
// (a: Graph, b: Map<Node, boolean>, c: number) => boolean
const mapValue = makeValue(prog.runArguments[0][0], new Map(), false) as CoreMapValue<PluginTypeEnvironment>;
mapValue.map.set(model.elements.get("1")!, makeValue(plugin.typeEnvironment, true, false));
mapValue.map.set(model.elements.get("2")!, makeValue(plugin.typeEnvironment, false, false));
```

You don't need to use `.set` (can pass a map with existing values in it) if you aren't mapping from core elements. `CoreElement` can't be passed, because `makeValue` expects it's second argument to be regular JS, not a CoreValue (which CoreElement is).

**Comment by danielscottjames** [comment]
If the State contains a map. (The circuit plugin has the input in each state object...), then Core throws an error after running the program and when trying to wrap up the States[] into CoreValues.

**Comment by Sheyne** [comment]
@RighteousRaichu it's cause by a line of code with 

    // todo: validate

Who would have thought?

**Comment by danielscottjames** [comment]
All of my CorePlaceholderValue's have the same type. They always say they're AndGate's. The UUID's are correct.

**Comment by Sheyne** [comment]
Oh it's definitely my fault. I'm working on it now.

**Comment by danielscottjames** [comment]
```
ERROR TypeError: a[Symbol.iterator] is not a function
    at CoreMapValue.load (eval at <anonymous> (file:///Users/Daniel/Development/sinap-ide/build/main.js:98:1), <anonymous>:1351:30)
    at new CoreMapValue (eval at <anonymous> (file:///Users/Daniel/Development/sinap-ide/build/main.js:98:1), <anonymous>:1334:18)
    at typeToValue (eval at <anonymous> (file:///Users/Daniel/Development/sinap-ide/build/main.js:98:1), <anonymous>:1540:20)
    at Object.makeValueFactory (eval at <anonymous> (file:///Users/Daniel/Development/sinap-ide/build/main.js:98:1), <anonymous>:1500:12)
    at Program.makeValue (eval at <anonymous> (file:///Users/Daniel/Development/sinap-ide/build/main.js:98:1), <anonymous>:704:23)
    at Program.run (eval at <anonymous> (file:///Users/Daniel/Development/sinap-ide/build/main.js:98:1), <anonymous>:718:29)
    at InputPanelComponent.run (eval at <anonymous> (file:///Users/Daniel/Development/sinap-ide/build/main.js:579:1), <anonymous>:164:33)
```

Edit: forgot to build, my bad

**Comment by danielscottjames** [comment]
Can deepListen work for maps?
Can deepEqual equate all elements by just UUID? So a node can deepEqual a sinap-pointer? (or reference?)

**Comment by Sheyne** [comment]
Now merged into legacy.

**Pull request closed without merging**
