### PR TITLE
typings as dependency

### LINKED ISSUE #15: Typescript Reference Path Messed Up
This is from the test folder. What needs to be set up for this to work? This directory does not exist on my machine even after an npm install.

```typescript
/// <reference path="../typings/globals/mocha/index.d.ts" />
```

### PR DESCRIPTION
**Pull request by Sheyne**
closes #15

### CODE REVIEW

**Comment by Sheyne** [comment]
@slaymaker1907 please review and merge

**Review by slaymaker1907 — CHANGES_REQUESTED** [review]
Could we put an install script that runs typings?

**Comment by Sheyne** [comment]
It can't be in the install script, because it's a dev dependency and the install script gets run regardless (I think). Theres a way to do it, but I don't know what it is. Do you want to look into it?

**Comment by slaymaker1907** [comment]
The issue is that it can't build without those typings. I tried running 

```bash
git clone
npm install
npm run build
```
And it would not build without those typings. What is the point of dev dependencies if it can't build without them for Sinap core?

EDIT: I think it makes sense to me now. I forgot that we were actually using NPM appropriately for sinap-core.

**Review by slaymaker1907 — APPROVED** [review]

**Pull request merged**
